### ISSUE TITLE
unclear about supported scenarios

### ISSUE THREAD

**Issue by tcurdt** [piotrkubisa/apigo#11]
It's unclear from the docs whether this just works for json req/res or whether it supports e.g. form encoded requests and sending binary responses e.g. images.

**Comment by piotrkubisa** [comment]
It does not matter if you are sending a binary, json or plain/text. All of them are supported, because they are standard Go features.

**Comment by piotrkubisa** [comment]
However, if I personally would need to accept or send back binary file based on few arguments (think: chart generation, with response 200KB+) I will strongly consider using "native" AWS Lambda request and response structs to make implementation as simple and fast as possible.

**Comment by tcurdt** [comment]
@piotrkubisa thanks for the clarification. Could you elaborate about the overhead a bit more?

While sending binary is straightforward natively (albeit being an annoying and non-streamable API where all has to be served from memory) I am not even sure how to receive binary content and decode forms easily without such a cushy layer in between.

**Comment by piotrkubisa** [comment]
About overhead, please take a look at a simple benchmark I made year ago - https://gist.github.com/piotrkubisa/03e04aaa8a4c5992189c556596f12689

It compares `apigo` to other libraries (ApiGateway-to-Go-net/http) and in simple example, all competitors presented 50+ allocations to proxy request. Please take it with a grain of salt, because it could have changed since last test run.

 Handling binaries in Go as in `apigo` will be provided in the `r *http.Request` variable and accessible via `r.Body`. The same I can say about JSON decoding. Form values and query strings are also provided in the `*http.Request` arg.

**Comment by tcurdt** [comment]
I have this example where I basically switch between `http` and `apigo` depending on whether it is local or on lambda.

```
package main

import (
	"log"
	"net/http"

	"github.com/go-chi/chi"
	_ "github.com/piotrkubisa/apigo"
)

func main() {
	http.ListenAndServe(":3000", routing())
	// apigo.ListenAndServe(":3000", routing())
}

func routing() http.Handler {

	r := chi.NewRouter()

	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("Hello World"))
	})

	r.Get("/id/{id}", func(w http.ResponseWriter, r *http.Request) {
		log.Printf("id: %s", chi.URLParam(r, "id"))
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("Hello World"))
	})

	return r
}
```

Why do I need to pass a domain to `apigo.ListenAndServe()`?
And I guess the lambda always listens on 80?

**Comment by tcurdt** [comment]
Seems to work just fine with just `:80`.

**Comment by piotrkubisa** [comment]
Sorry for providing ambiguous name without proper explanation in the godoc, but it is not `port` nor `bind` but `host` (actually a FQDN, like `example.com`). It might be `a123456789.execute-api.eu-west-1.amazonaws.com` or custom domain name configured in the `AWS API Gateway`. Note: It should work even if the `host` variable was empty or provided a dummy value.

I have provided it to protect against certain malformed request with `Host` header (e.g. host-header attacks). Provided `host` value is going to be hardcoded in the `r.URL.Host` value:
https://github.com/piotrkubisa/apigo/blob/97eab6fbab48178accf982e935ee07d23c5a50b6/request.go#L92

**Comment by tcurdt** [comment]
Ah, I see. Having the lambda URL hardcoded isn't really great though.
Is there a way to pass this on from the gateway? Or how do you use this in a real-life setup?

**Comment by piotrkubisa** [comment]
I was passing that value (lambda URL) by the `Fn::Ref` in the `Cloud Formation` as a environment variable. However, if you are sure you want to automagically set value based on the actual host header, then you may just reimplement the default proxy to do that just [like apex/gateway do](https://github.com/apex/gateway/blob/master/request.go#L84). 

Anyway, if you are not experienced enough in Lambda runtime and their request/response structures I believe `apex/gateway` will be a better fit for you than `apigo`. It has almost the same implementation in terms of proxying requests as `apigo` and overall I believe it might be even simpler to use.

**Comment by tcurdt** [comment]
Is there a particular reason you decided to diverge from how apex/gateway does it? Just trying to understand the reasoning.

**Comment by piotrkubisa** [comment]
I forked `apex/gateway` to have tailored implementation for the proxy that I was using. I was missing few things (i.e. base-path stripping) and noticed few things can be done way better if the whole code would be changed (`apex/gateway` was too opinionated to me), like:
* Define custom proxy transformer and limit request operations or add some new step.
* Quite easy to access to the `event` value.
* Having dedicated-function to use only certain operations (I don't have to proxy a whole request, just few values). Example: `ParseURL`, `ParseBody`.
* Written-down recipes how to transform the `ApiGateway` events, if somebody executes "A little copying is better than a little dependency" proverb.
* Aforementioned `StripBasePath` transformer.
* Few minor fixes around transforming.
* Better benchmark results, but who cares...

Please note, at this moment I don't know anyone who uses my library, there might be no third-party use at all. Additionally, it is sparsely documented and currently I am not really eager to do any maintenance work, because I don't host any Go apps on Lambda - I don't see any dogfooding/incentive from it.

I am suggesting using `apex/gateway` anyone, who don't understand implementation of the `apigo` - It will be definitely way quicker to put it as a depedency and forget.

**Comment by tcurdt** [comment]
Thanks a lot for the explanation!
You should put that in the README.
